"use client";
import { useState } from "react";
import { generateQuestions, type GeneratedQuestion } from "./product-views";
import { questionEngineInfo } from "@/lib/question-engine";

type Batch={domain:string;difficulty:string;generated:number;passed:number;failed:number;issues:string[]};
const domains=["Algebra","Advanced Math","Problem Solving & Data","Geometry & Trig"],difficulties=["Foundations","Medium","Challenge"];
function inspect(question:GeneratedQuestion){const issues:string[]=[];if(!question.prompt.trim())issues.push("Empty prompt");if(question.answers.length!==4)issues.push("Not four choices");if(new Set(question.answers).size!==question.answers.length)issues.push("Duplicate choices");if(question.correct<0||question.correct>=question.answers.length)issues.push("Invalid answer index");if(!question.explain.trim())issues.push("Missing explanation");if(!question.domain||!question.skill)issues.push("Missing metadata");if(!question.templateId||!question.templateVersion||!question.seed)issues.push("Missing reproducibility data");return issues}

export function QualityLab(){
  const [batches,setBatches]=useState<Batch[]>([]),[running,setRunning]=useState(false),[lastRun,setLastRun]=useState("");
  const run=()=>{setRunning(true);window.setTimeout(()=>{const results=domains.flatMap(domain=>difficulties.map(difficulty=>{let passed=0,failed=0;const issueSet=new Set<string>();for(let batch=0;batch<20;batch++){generateQuestions(10,domain,difficulty).forEach(question=>{const issues=inspect(question);issues.length?failed++:passed++;issues.forEach(issue=>issueSet.add(`${question.skill}: ${issue}`))})}return{domain,difficulty,generated:200,passed,failed,issues:Array.from(issueSet)}}));setBatches(results);setLastRun(new Date().toLocaleTimeString([], {hour:"numeric",minute:"2-digit"}));setRunning(false)},20)};
  const total=batches.reduce((sum,batch)=>sum+batch.generated,0),failed=batches.reduce((sum,batch)=>sum+batch.failed,0);
  return <main className="quality-shell"><header><a href="/studio">← Orbit Studio</a><div><span>CONTENT QUALITY · ENGINE V{questionEngineInfo.version}</span><h1>Generator quality lab</h1></div><button onClick={run} disabled={running}>{running?"Running 2,400 variants…":"Run full validation"}</button></header><section className="quality-summary"><div><span>VARIANTS TESTED</span><b>{total.toLocaleString()}</b></div><div><span>VALIDATION RATE</span><b>{total?`${Math.round((total-failed)/total*1000)/10}%`:"—"}</b></div><div><span>ISSUES FOUND</span><b className={failed?"bad":""}>{total?failed:"—"}</b></div><div><span>TEMPLATES</span><b>{questionEngineInfo.templateCount}</b></div></section><section className="quality-info"><div><span>WHAT THIS CHECKS</span><h2>Every built-in family, across every difficulty.</h2><p>The lab validates choices, answer keys, explanations, skill metadata, template versions, and the seed required to recreate every question.</p></div><code>4 domains × 3 difficulties × 200 variants = 2,400 checks</code></section>{batches.length?<section className="quality-table"><header><span>DOMAIN</span><span>DIFFICULTY</span><span>GENERATED</span><span>PASSED</span><span>FAILED</span></header>{batches.map(batch=><article key={`${batch.domain}-${batch.difficulty}`} className={batch.failed?"has-issues":""}><strong>{batch.domain}</strong><span>{batch.difficulty}</span><span>{batch.generated}</span><span>{batch.passed}</span><b>{batch.failed}</b>{batch.issues.length>0&&<details><summary>View issues</summary>{batch.issues.map(issue=><p key={issue}>{issue}</p>)}</details>}</article>)}</section>:<section className="quality-empty"><span>✓</span><h2>Ready when you are.</h2><p>Run validation after changing generator rules or before publishing a new build.</p></section>}</main>
}
